# Generated by Django 4.1.1 on 2022-09-27 13:17

from django.db import migrations, models
import essesntials.models


class Migration(migrations.Migration):

    dependencies = [
        ('essesntials', '0004_article_author_articleseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/8.jpg', max_length=255, upload_to=essesntials.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/8.jpg', max_length=255, upload_to=essesntials.models.ArticleSeries.image_upload_to),
        ),
    ]
